package okuken.iste.migration.scripts;

public class V00006_ImproveAuthApply implements PrefixedMigrationScript {

	@Override
	public String getUpScript() {
		return  "ALTER TABLE ISTE_AUTH_APPLY_CONFIG ADD COLUMN SOURCE_TYPE INTEGER DEFAULT 0;\n" +
				"ALTER TABLE ISTE_AUTH_APPLY_CONFIG RENAME COLUMN VAR_NAME TO SOURCE_NAME;\n" +
				"ALTER TABLE ISTE_AUTH_APPLY_CONFIG ADD COLUMN ENCODE TEXT;\n" +
				"\n"+
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN FIELD06 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN FIELD07 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN FIELD08 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN FIELD09 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN FIELD10 TEXT;\n" +
				"\n"+
				"ALTER TABLE ISTE_AUTH_ACCOUNT RENAME COLUMN SESSION_ID TO SESSION_ID01;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID02 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID03 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID04 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID05 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID06 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID07 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID08 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID09 TEXT;\n" +
				"ALTER TABLE ISTE_AUTH_ACCOUNT ADD COLUMN SESSION_ID10 TEXT;\n";
	}

}
